build: off
cache:
- "c:\\sr -> appveyor.yml"

before_test:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
# make sure stack.exe is on the PATH even when Hadrian changes directory
- set PATH=C:\project;%PATH%
# match the Hadrian resolver, so we download less stuff
- stack init ghc-lib-gen --resolver=lts-12.10
- stack setup > nul
- stack exec -- pacman -S autoconf automake-wrapper make patch python tar --noconfirm
- echo "" | stack --no-terminal build ghc-lib-gen
- git clone git://git.haskell.org/ghc.git --recursive
- stack exec -- ghc-lib-gen ghc
# stack init doesn't work because of https://github.com/commercialhaskell/stack/issues/4508
- echo - examples/mini-hlint >> stack.yaml
- echo - ghc >> stack.yaml
- stack build --flag ghc-lib:with-heap-prim
- stack exec -- mini-hlint examples/mini-hlint/test/MiniHlintTest.hs
