build: off
cache:
- "c:\\sr -> appveyor.yml"

before_test:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- set PATH=C:\project;%PATH%
- stack init ghc-lib-gen
- stack setup > nul
- echo "" | stack --no-terminal build ghc-lib-gen
- git clone git://git.haskell.org/ghc.git --recursive
- stack exec -- ghc-lib-gen ghc
