build: off
cache:
- "c:\\sr -> appveyor.yml"

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
# Make sure stack.exe is on the PATH even when Hadrian changes directory
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe
- set PATH=C:\project;%PATH%

- stack setup > nul
- stack exec -- pacman -S autoconf automake-wrapper make patch python tar --noconfirm
- stack --no-terminal build ghc-lib-gen
- stack exec runhaskell CI.hs
