build: off
cache:
- "c:\\sr -> appveyor.yml"

before_test:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
# make sure stack.exe is on the PATH even when Hadrian changes directory
- set PATH=C:\project;C:\Python37-x64;%PATH%
- python --version
- python3 --version
# match the Hadrian resolver, so we download less stuff
- stack init ghc-lib-gen --resolver=lts-12.10
- stack setup > nul
- echo "" | stack --no-terminal build ghc-lib-gen
- git clone git://git.haskell.org/ghc.git --recursive
- stack exec -- ghc-lib-gen ghc
